### ISSUE TITLE
Re-render 2.0.1

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/stack-feedstock#5]
Please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) this feedstock with `conda-smithy` 2.0.1 as it is very out-of-date.

**Comment by eggzilla** [comment]
Done :-)

**Comment by eggzilla** [comment]
hups, just re-rendered the fork

**Comment by jakirkham** [comment]
Thanks. Feel free to close.

Would recommend doing a PR next time to just make sure that it doesn't break anything before going into `master`.

**Comment by eggzilla** [comment]
Ok, next time I will do it via PR, closing
